var x = 7;
var y;
var result;
y = 5;
result = x + y;
document.write(result);
result += x;
document.write("<br>" + result);
document.write("<br>");
document.write(x + "+" + y + "=" + (x + y));
document.write("<br>");
var str_1 = "12";
var str_2 = Number("24");
document.write(Number(str_1) + str_2);
document.write("<br>");
var bool;
var z = 6;
var r = 7;
bool = z >= r;
document.write(bool);
document.write("<br>");
document.write(10 + "%" + 7 + "=" + (10%7));